# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
