# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpart',
            name='expire_date',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
