# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productpart_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpart',
            name='part_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
