# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180407_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpart',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
